esphome:
  name: esphome-web-68879c
  friendly_name: TestClimateController

esp32:
  variant: esp32
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:
- platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

web_server:
  port: 80

uart:
  tx_pin: GPIO17
  rx_pin: GPIO16
  baud_rate: 4800
  parity: EVEN

time:
  - platform: sntp


    



external_components:
  - source: github://hopsydev/grees
    components: [sinclair_ac]
    refresh: 0s

climate:
  - platform: sinclair_ac
    name: TestClimate
    horizontal_swing_select:
      name: TestClimate Horizontal Swing Mode
    vertical_swing_select:
      name: TestClimate Vertical Swing Mode
    display_select:
      name: TestClimate Display Mode
    display_unit_select:
      name: TestClimate Display Unit
    plasma_switch:
      name: TestClimate Plasma
    beeper_switch:
      name: TestClimate Beeper      
    sleep_switch:
      name: TestClimate Sleep
    xfan_switch:
      name: TestClimate X-fan
    save_switch:
      name: TestClimate Save/8 Heat  